"""Account UI informed by Logto's account layouts, implemented for server sessions."""
STYLE = '''
:root{color-scheme:light dark;--bg:#f6f6f3;--surface:#fff;--text:#262820;--muted:#72766b;--line:#e3e5dd;--field:#fff;--accent:#333b2b;--on-accent:#fff;--soft:#eeefe8;--focus:#778960;--danger:#b44949}
@media(prefers-color-scheme:dark){:root{--bg:#161815;--surface:#242722;--text:#f0f1eb;--muted:#a8aea0;--line:#3c4136;--field:#242722;--accent:#dce3ce;--on-accent:#22281c;--soft:#30352b;--focus:#afc28f;--danger:#f19d96}}
body{background:var(--bg);color:var(--text);font:15px/1.6 -apple-system,BlinkMacSystemFont,"Segoe UI","Noto Sans CJK SC","Microsoft YaHei",sans-serif;min-width:960px;-webkit-font-smoothing:antialiased}
header{max-width:1120px;height:96px;padding:24px 32px;border:0}.brand{font-size:16px;letter-spacing:3px}.brand::after{content:'ACCOUNT';font-size:10px;letter-spacing:2px;font-weight:500;color:var(--muted);margin-left:22px;padding-left:22px;border-left:1px solid var(--line)}
main{max-width:1040px;margin:28px auto 64px;padding:0 32px 40px}h1{font-family:inherit;font-size:30px;font-weight:650;letter-spacing:-.8px;margin:0 0 28px}h2{font-size:16px;font-weight:600;line-height:1.5}p{margin:8px 0 20px}.muted{color:var(--muted)}
.account-tabs{gap:8px;border-bottom:1px solid var(--line);padding:0 0 18px;margin-bottom:32px}.account-tabs a{padding:9px 18px;border-radius:8px;color:var(--muted);font-weight:500}.account-tabs a:hover{color:var(--text);background:var(--soft);text-decoration:none}.account-tabs a[aria-current=page]{background:var(--soft);color:var(--text)}
.account-card{background:var(--surface);border:1px solid var(--line);padding:24px 28px;border-radius:16px;margin:16px 0}.account-row p{margin:4px 0 0;color:var(--muted)}.account-row>a{padding:8px 16px;border:1px solid var(--line);border-radius:8px;font-weight:500;font-size:14px}.account-row>a:hover{background:var(--soft);text-decoration:none}
button{display:inline-flex;align-items:center;justify-content:center;min-height:44px;padding:11px 22px;border:1px solid transparent;border-radius:10px;background:var(--accent);color:var(--on-accent);font-family:inherit;font-size:14px;font-weight:600;line-height:1.4;transition:opacity .15s,background .15s}button:hover{opacity:.88}button:disabled{opacity:.5;cursor:wait}a:focus-visible,button:focus-visible,input:focus-visible{outline:2px solid var(--focus);outline-offset:3px}
main:has(>.flow)>h1,main:has(>.flow)>.account-tabs{display:none}main:has(>.flow){margin-top:12px}.flow{max-width:540px;margin:40px auto 16px;background:var(--surface);border:1px solid var(--line);border-radius:22px;padding:32px 44px 40px;box-shadow:0 16px 60px #00000008}.flow .back{display:inline-flex;gap:8px;color:var(--muted);font-size:14px;margin-bottom:32px}.flow h2{font-size:26px;letter-spacing:-.5px;margin-bottom:10px}.flow .description{font-size:14px;color:var(--muted);line-height:1.8;margin-bottom:26px}.flow form{margin:0}.flow button[type=submit]{width:100%;margin-top:8px}.flow .alternative{text-align:center;font-size:13px;color:var(--muted);margin:22px 0 0}.flow .alternative a{color:var(--text);text-decoration:underline;text-underline-offset:4px}.flow .step{font-size:11px;font-weight:600;letter-spacing:2px;color:var(--muted);margin-bottom:14px}
.profile-field{position:relative;max-width:none;margin:22px 0}.profile-field input{width:100%;min-height:52px;background:var(--field);border:1px solid var(--line);border-radius:10px;padding:15px 16px;color:var(--text);font:inherit;margin-top:8px;box-shadow:none}.profile-field input:read-only{color:var(--muted);background:var(--soft)}.profile-field input[name=code]{font-size:24px;letter-spacing:8px;text-align:center}.field-label{font-size:13px;font-weight:500;color:var(--muted)}.flow .profile-field{margin:20px 0}.flow .profile-field input{margin-top:8px}.feedback{padding:12px 14px;border-radius:8px;background:var(--soft);font-size:13px;line-height:1.6;margin:18px 0;color:var(--text)}
.profile-intro{padding:24px 0;margin:0 0 24px}.profile-avatar{background:var(--soft);color:var(--text);width:72px;height:72px}.profile-intro h2{font-size:22px}main>form{background:var(--surface);padding:20px 28px 28px;border:1px solid var(--line);border-radius:16px}main>form .profile-field{max-width:640px}article{background:var(--surface);border:1px solid var(--line);border-radius:14px;padding:22px 26px;margin:14px 0;position:relative}article button{background:var(--soft);color:var(--text);font-size:13px;min-height:38px}article p{font-size:13px}.account-footer{margin:40px 0 0;text-align:center;color:var(--muted);font-size:11px;letter-spacing:1px}
body .fujioky-menu-inner{background:var(--surface);color:var(--text);border-color:var(--line)}body .fujioky-user .fujioky-menu a{color:var(--text)!important}body .fujioky-menu a:hover{background:var(--soft)}body .fujioky-menu-email{color:var(--muted);border-color:var(--line)}

html{min-height:100%}body{min-height:100vh;display:flex;flex-direction:column}body>header{width:100%;flex-shrink:0}body>main{width:100%;flex:1;margin-bottom:0}body>header .brand,body>header .brand:hover,body>header .brand:focus{text-decoration:none!important;border:0}body>header .brand::after{content:none}body>header .brand picture{display:block}body>header .brand img{display:block;width:160px;height:48px;object-fit:contain;object-position:left center}.account-footer{width:calc(100% - 64px);max-width:1040px;margin:36px auto 0;padding:24px 0;display:flex;justify-content:space-between;align-items:center;gap:24px;border-top:1px solid var(--line);font-size:11px;letter-spacing:.2px;color:var(--muted);flex-shrink:0}.account-footer span:last-child{font-size:10px;letter-spacing:1.8px}
'''
